moneyInput = input("Insert the amount of money: ")
amountOfPeople = input("Insert the amount of people ")
productValue = int(moneyInput)/float(amountOfPeople)
productValieText = format(productValue, ".2f")
print("By average, you would get", productValueText, "Bath per person.")
print("By average, you would get " + productValueText +" Bath per person.")
print("By average, you would get {} Bath per person.".format(productValueText))
print(f"By average, you woukd get {productValueText} Bath per person.")